services:
  control_plane:
    image: golang:1.21.1
    command: go run .
    working_dir: /app/src/controlplane
    volumes:
      - ./:/app
  dummy_server:
    image: golang:1.21.1
    command: go run .
    working_dir: /app/src/dummycluster
    volumes:
      - ./:/app
  envoy:
    build:
      dockerfile: envoy-with-kuma-tp.Dockerfile
    ports:
      - "15001:15001"
      - "9901:9901"
    privileged: true
    volumes:
      - ./examples/envoy.yaml:/etc/envoy/envoy.yaml
